добавил анализатор
razor3538/go-service-shortener-url pull request #20
Opened 2023-03-26 15:15 UTC by razor3538

2023-03-28 11:30 UTC, rktkov requested changes
1. Я бы отказался от использования функции println и объявил бы пакет с логгированием, в котором бы реализовал все необходимые методы коммуникации.
2. Я бы переструктурировал бы пакеты проекта, убрав все кроме profiles  в папку internals.

2023-03-28 11:30 UTC, rktkov commented on tools/error_creator.go
> +func CreateError(code int, requestErr error, c *gin.Context) {
Не думаю, что этому методу место в пакете tools. Он использует структуры из внешнего пакет, тем самым связывает общий пакет тулз с конкретной реализацией, в данном случае, роутера хттп сервера. Лучше его вынести ближе к коду, где он используется, т.е. в пакет где реализовывается функционал завязанный на gin. Хороший самостоятельный тест зависимостей - представь, что тебе по какой-либо причине придется менять библиотеку http роутинга, очень странно что придется менять код в этом пакете.

2023-04-05 09:36 UTC, rktkov requested changes

2023-04-05 09:36 UTC, rktkov commented on internal/app/api/shortApi.go
> +	"example.com/m/v2/internal/app/models"
Перепутались импорты.

2023-04-05 09:36 UTC, rktkov commented on cmd/staticlint/multichecker/cmd/multichecker.go
> +	"golang.org/x/tools/go/analysis"
Перепутались пакеты.

2023-04-05 09:36 UTC, rktkov commented on internal/config/init.go
> +		println(err)
println стоит изменить на использование внутреннего пакета логгирования, внутри которого использовать либо пакет fmt, либо какой-либо внешний пакет логгирования.

2023-04-27 16:41 UTC, widler reviewed
Общее замечание по всему проекту, ты очень сильно нарушил принципы низкой связности(подробнее про это вот тут https://habr.com/ru/companies/otus/articles/505852/)
и внедрения зависимостей (можешь посмотреть мой вебинар, там про то как лучше сделать спринты с 1-4 https://disk.yandex.ru/d/EHzgoysp3Q3BDw)

2023-04-27 16:41 UTC, widler commented on internal/app/api/shortApi.go
> +	"example.com/m/v2/internal/app/models"
импорты надо оформить в соответствии с этими рекомендациями https://github.com/uber-go/guide/blob/master/style.md#import-group-ordering

2023-04-27 16:41 UTC, widler commented on internal/config/db.go
> +		if err != nil {
Смотри, здесь сразу несколько замечаний, 
1) Задание не подразумевает использование gorm - надо переделать.
2) В задании чётко указан тип БД - postgres, ты используешь sqlite при этом у тебя функция подразумевает использование  MySQL
3) Создавать соединение с БД в пакете с конфигурацией, весьма неожиданно и модет вызвать проблемы с пониманием твоего кода.

2023-04-28 09:01 UTC, razor3538 commented on internal/config/db.go
> +		if err != nil {
1 - я не буду переделать весь проект. Учусь здесь я уже пол года и мне впервые говорят за то что горм нельзя было использовать.
2 - в задание четко указана постгря ТОЛЬКО если пришел нужный флаг или переменная среды. В остальных случаях чтение и запись должна быть в файл. Файл sqlite позволен по вашим автотестам.
3 - куда тогда это вынести?
4 - почему проверяется код не из задания, а тот который уже был принят и оценен?

2023-04-28 14:07 UTC, widler commented on internal/config/db.go
> +		if err != nil {
Хорошо, я посоветовался с куратором и твоим предыдущим ментором они попросили убрать замечания к коду БД.
Оформи импорты в соответствии с рекомендациями, посмотри вебинар и если хочешь назначай 1-1 обсудим, какие проблемы могут быть в твоём коде и как их избежать.

2023-05-03 07:33 UTC, merged